/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medbot;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.text.DefaultCaret;


public class MedBotFrame extends javax.swing.JFrame {

    String msg="";
    int k=1;
    ArrayList medbotquestions=new ArrayList();
    ArrayList useranswers=new ArrayList();
    String userchoice="";
    public MedBotFrame() {
        super("MedBot");
        initComponents();
        jTextPane1.setEditable(false);
        jTextPane1.setContentType("text/html");
      
        jScrollPane1.getVerticalScrollBar().addAdjustmentListener(
                e -> {
                    if ((e.getAdjustable().getValue() - e.getAdjustable().getMaximum()) >
                            -jScrollPane1.getHeight() - 500) {
                        e.getAdjustable().setValue(e.getAdjustable().getMaximum());
                    }
                });

        msg="<html><font size='5'><img src='" + getClass().getResource("/bot1.gif").toString() +"'/>"
                + "<b>Medbot</b>: Hi this is automated Medbot, Please Answer these Questions"
                + "<br/><br/>a. You feel chest pain?"
                + "<br/>b. You feel shortness in breath?"
                + "<br/>c. You see blood in urine?"
                + "<br/>Please enter your options</font></html>";
        jTextPane1.setText(msg);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 410, 550);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(0, 555, 300, 60);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/send.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 555, 110, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
         String userreply=jTextField1.getText();
         jTextField1.setText("");
       
        if(userreply.isEmpty())
        {
         JOptionPane.showMessageDialog(null, "Plesae reply to medbot questions.");     
        }
      
        else 
        {
          if(userreply.equals("a")) 
          {
              user_reply(userreply);
              msg = msg.replace("<html>", "");
              msg = msg.replace("</html>", "");
              msg = "<html><font size='5'>" + msg
                      + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                      + "<b>Medbot</b>: " + "You have a possibility of Heart Disease"
                      + "<br/><b>Medbot</b>: " + "Please Answer the following Questions to help you"
                      + "</font></html>";
              jTextPane1.setText(msg);
              userchoice="a";
          }
          if(userreply.equals("b")) 
          {
              user_reply(userreply);
              msg = msg.replace("<html>", "");
              msg = msg.replace("</html>", "");
              msg = "<html><font size='5'>" + msg
                      + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                      + "<b>Medbot</b>: " + "You have a possibility of Covid 19"
                      + "<br/><b>Medbot</b>: " + "Please Answer the following Questions to help you"
                      + "</font></html>";
              jTextPane1.setText(msg);
              userchoice="b";
          }
          if(userreply.equals("c")) 
          {
              user_reply(userreply);
              msg = msg.replace("<html>", "");
              msg = msg.replace("</html>", "");
              msg = "<html><font size='5'>" + msg
                      + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                      + "<b>Medbot</b>: " + "You have a possibility of Kidney Disease"
                      + "<br/><b>Medbot</b>: " + "Please Answer the following Questions to help you"
                      +"</font></html>";
              jTextPane1.setText(msg);
              userchoice="c";
          }
          
          if(userchoice.equals("a"))
          {
              if(k==1)
              {
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "Please enter your age" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("Please enter your age");
                  k=2;
                 
              }
             
             if (isDouble(userreply) == true) 
             {
               if(medbotquestions.get(medbotquestions.size()-1).equals("Please enter your age")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "Please enter your chest pain level" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("Please enter your chest pain level");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("Please enter your chest pain level")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "Please enter your trestbps" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("Please enter your trestbps");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("Please enter your trestbps")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "Please enter your cholestrol" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("Please enter your cholestrol");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("Please enter your cholestrol")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "Please enter your fasting blood sugar" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("Please enter your fasting blood sugar");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("Please enter your fasting blood sugar")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "Please enter your restecg" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("Please enter your restecg");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("Please enter your restecg")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "Please enter your maximum heart rate" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("Please enter your maximum heart rate");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("Please enter your maximum heart rate")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  String medbotreply=new ProcessInit().getDiseaseResult(useranswers,"heart");
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + medbotreply + "</font></html>";
                  jTextPane1.setText(msg);
                  
                   
               }
             }
             
             else if(!userreply.equals("a")&& !userreply.equals("b") && !userreply.equals("c") && isDouble(userreply) == false)
             {
               JOptionPane.showMessageDialog(null, "User reply should be in numeric only");    
             }
             
            
          }
          
          if(userchoice.equals("b"))
          {
              if(k==1)
              {
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "Please enter your gender 0 for female and 1 for male" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("Please enter your gender 0 for female and 1 for male");
                  k=2;
                 
              }
             
             if (isDouble(userreply) == true) 
             {
               if(medbotquestions.get(medbotquestions.size()-1).equals("Please enter your gender 0 for female and 1 for male")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "If you have cough if yes enter 1 for no enter 0" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("If you have cough if yes enter 1 for no enter 0");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("If you have cough if yes enter 1 for no enter 0")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "If you have fever if yes enter 1 for no enter 0" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("If you have fever if yes enter 1 for no enter 0");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("If you have fever if yes enter 1 for no enter 0")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "If you have sore throat if yes enter 1 for no enter 0" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("If you have sore throat if yes enter 1 for no enter 0");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("If you have sore throat if yes enter 1 for no enter 0")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "If you have shortness of breath if yes enter 1 for no enter 0" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("If you have shortness of breath if yes enter 1 for no enter 0");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("If you have shortness of breath if yes enter 1 for no enter 0")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "If you have headache if yes enter 1 for no enter 0" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("If you have headache if yes enter 1 for no enter 0");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("If you have headache if yes enter 1 for no enter 0")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "If you have weakness if yes enter 1 for no enter 0" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("If you have weakness if yes enter 1 for no enter 0");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("If you have weakness if yes enter 1 for no enter 0")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  String medbotreply=new ProcessInit().getDiseaseResult(useranswers,"covid");
                  medbotreply=medbotreply.replace("\n", "<br/>");
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + medbotreply + "</font></html>";
                  jTextPane1.setText(msg);
                  
                   
               }
             }
             
             else if(!userreply.equals("a")&& !userreply.equals("b") && !userreply.equals("c") && isDouble(userreply) == false)
             {
               JOptionPane.showMessageDialog(null, "User reply should be in numeric only");    
             }
             
            
          }
           
          if(userchoice.equals("c"))
          {
              if(k==1)
              {
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "Please enter your age" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("Please enter your age");
                  k=2;
                 
              }
             
             if (isDouble(userreply) == true) 
             {
               if(medbotquestions.get(medbotquestions.size()-1).equals("Please enter your age")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "Please enter your albumin level" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("Please enter your albumin level");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("Please enter your albumin level")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "Please enter your blood glucose level" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("Please enter your blood glucose level");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("Please enter your blood glucose level")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "Please enter your blood urea level" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("Please enter your blood urea level");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("Please enter your blood urea level")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "Please enter your serum creatinine level" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("Please enter your serum creatinine level");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("Please enter your serum creatinine level")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "Please enter your hemoglobin level" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("Please enter your hemoglobin level");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("Please enter your hemoglobin level")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + "If you have diabetes enter 0 for no 1 for yes" + "</font></html>";
                  jTextPane1.setText(msg);
                  medbotquestions.add("If you have diabetes enter 0 for no 1 for yes");
                   
               }
               else if(medbotquestions.get(medbotquestions.size()-1).equals("If you have diabetes enter 0 for no 1 for yes")) 
               {
                  user_reply(userreply);
                  useranswers.add(userreply);
                  String medbotreply=new ProcessInit().getDiseaseResult(useranswers,"kidney");
                  msg = msg.replace("<html>", "");
                  msg = msg.replace("</html>", "");
                  msg = "<html><font size='5'>" + msg
                          + "<br/><br/><img src='" + getClass().getResource("/bot1.gif").toString() + "'/>"
                          + "<b>Medbot</b>: " + medbotreply + "</font></html>";
                  jTextPane1.setText(msg);
                  
                   
               }
             }
             
             else if(!userreply.equals("a")&& !userreply.equals("b") && !userreply.equals("c") && isDouble(userreply) == false)
             {
               JOptionPane.showMessageDialog(null, "User reply should be in numeric only");    
             }
             
            
          }
        } 
        
      
        System.out.println("useranswers: "+useranswers);
                
       
    }//GEN-LAST:event_jButton1ActionPerformed

    
    void user_reply(String userreply) 
    {
        userreply = userreply.trim().toLowerCase();
        msg=msg.replace("<html>", "");
        msg=msg.replace("</html>", "");
        msg="<html><font size='5'>"+msg
                + "<br/><br/><img src='" + getClass().getResource("/user.png").toString() +"'/>"
                + "<b>User</b>: "+userreply+"</font></html>";
        
        
        jTextPane1.setText(msg);
        
    }
    
    boolean isDouble(String str)
    {
        try
        {
          Double.parseDouble(str);
           return true;  
        }
        catch (Exception e)
        {
            return false;
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedBotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedBotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedBotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedBotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedBotFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
